### ISSUE TITLE
Create Suggestion models 

### ISSUE THREAD

**Issue by heytherewill** [toggl/ios#10]
## Description
We need to create the suggestion model. It should copy the implementation that currently exists in the Xamarin app. We also need to add a case to the `TimeEntryViewModel` discriminated union that represents a suggestion (it can be a simple wrapper).

## Definition of done
- [ ] The suggestion type is created
- [ ] The `TimerState.LocalState` type should have a property to hold the list of suggestions
- [ ] These properties get mapped to `TimeEntriesLogState`
- [ ] When performing the mapping from `List<TimeEntry>` into a `List<TimeEntryViewModel>`, we should add the suggestions at the top
- [ ] We should add unit tests to check that the mapping function is behaving accordingly (specially since it will grow a lot once we start adding grouping behavior)

**Comment by Odrakir** [comment]
I already mentioned this, but I disagree with the details of the implementation as described above. Suggestions should not be part of the TimeEntryViewModel list.

These are two different app features that should be tested separately. The fact that Android uses the same recycler view to show all this doesn't justify for that way of organising code in iOS (I would argue that not even Android should do this)
