### ISSUE TITLE
Update the DescriptionEntered action to include the cursor position

### ISSUE THREAD

**Issue by heytherewill** [toggl/ios#120]
## Description
Since we are implementing the suggestion mechanism, the current position of the cursor is pretty important.
It doesn't need to be stored in the state, since it'll just be later used by an effect to calculate the suggestions
Emitting this action when the cursor changes should be handled in another issue.
## Definition of done
- [x] The action is updated to match the docs
- [x] The place where the action is dispatched is changed to return the cursor position as well 
- [x] The documentation is updated to reflect the changes done in this PR

**Comment by Odrakir** [comment]
🤔 Can you remind me why we need the cursor position in the reducer?

**Comment by sofokli1** [comment]
@heytherewill I think the above comment is for you. Can you take a look?

**Comment by heytherewill** [comment]
We solved this internally, but the tl;dr is that this is the implementation that takes into account all the edge cases. You can proceed with this issue normally :)
