### ISSUE TITLE
Properly display the current duration 

### ISSUE THREAD

**Issue by heytherewill** [toggl/ios#121]
## Description
We need to ensure that the duration on the top right corner of the card is correct
## Definition of done
- [ ] If the duration is set, we just use it along with the existing format method used in the log
- [ ] If there's no duration, we calculate the duration based on the current date and then use the existing format method
- [ ] If there's no duration, we need to update the number every second

**Comment by Odrakir** [comment]
🤔 If we are starting a new TE there's no duration, right? Because we were changing the behaviour of this to only start when the user actually taps the done button. Or am I wrong?

**Comment by pdrj** [comment]
You're right. As long as in
> If we are starting a new TE there's no duration
'starting' actually means tapping the empty description field. In this case, on Android we just display a zero duration (as the TE is not running yet). Otherwise (TE started via the play button), the duration is calculated and updated each second.

**Comment by Odrakir** [comment]
uh? If the user hits the play button you show this view? I thought that would be a fast way of starting an empty entry. Meaning, we won't show this view, just start a new TE and show it in the running time entry log.

Also, I'm not sure if it makes sense to show the duration at all for new TEs that will have a duration of 0.

**Comment by pdrj** [comment]
Right, sorry for the play button confusion. We thought about bringing up the card when play button is pressed, but we're currently not doing it.

**Comment by heytherewill** [comment]
> If we are starting a new TE there's no duration, right? Because we were changing the behaviour of this to only start when the user actually taps the done button. Or am I wrong?

Yes, but you can still edit a running time entry

**Comment by Odrakir** [comment]
I know. But in the case of a new TE we won't display the duration label then.
