### ISSUE TITLE
Add build configuration files

### ISSUE THREAD

**Issue by Odrakir** [toggl/ios#128]
## Description
Adding new projects and targets to the app is a bit messy. There's many changes to the build configuration that need to be done and it's very error prone.

This can be solved by using build configuration files in Xcode: [xcconfig files](https://nshipster.com/xcconfig/)

## Definition of done
- [ ] We end up with all the needed configuration files for static frameworks, dynamic frameworks, tests and the main app. I'm not sure how that would look, if we need 4 different files or not. Some research needs to be done
- [ ] Said configuration allows to add new modules without much hassle

**Comment by sofokli1** [comment]
@Odrakir do you have a list of changes that are needed in the config file in our case? (or a screen capture video showing all the needed changes if it is easier for you)
