### ISSUE TITLE
Create the WheelForegroundView

### ISSUE THREAD

**Issue by daividssilverio** [toggl/ios#150]
## Description
The [WheelForegroundView](https://github.com/toggl/mobileapp/blob/develop/Toggl.iOS/Views/EditDuration/WheelForegroundView.cs) does the following:
  - Draws the rainbow overlapping arcs between start end end times of a time entry
  - Draws the start/end time editing handles
  - Handles touch interaction
  - Provides interfaces to control the widget and its represented values

## Dependencies
Needs the Math on #147  
Depends on #148 

## Definition of done

- [x] The wheel foreground custom view is created

Drawing:

- [x] It draws start end end editing handles for stopped time entries
- [x] It draws only the start editing handle for running time entries, drawing the end of the wheel arc as "now"
- [x] It draws rainbow coloured arcs/wheels based on the number of hours loops (1 loop = 1 hour)
- [x] It considers dark mode

Touch interaction:

- [x] It handles touch interaction when moving the editing handles
- [x] It handles touch interaction when moving the wheel arcs
- [x] It provides haptic feedback when handling the handles/arcs for every minute swirled

Interface:

- [x] It has configurable minimum and maximum start end end times
- [x] It provides an interface to configure the wheel as in "running mode" to represent running time entries
- [x] It provides an interface to set the start time
- [x] It provides an interface to set the end time
- [x] It emits events when start/end times are changed due to user interaction

**Comment by heytherewill** [comment]
I started working on this, but turns out there are a bunch of details so this is better off worked by @juanlaube since he knows his way around dates much better. 

Temp work can be found here: https://github.com/toggl/ios/tree/wheeeeeeeeeel
