### ISSUE TITLE
Add the StartTimeDragged action

### ISSUE THREAD

**Issue by juanlaube** [toggl/ios#206]
## Description

Add the StartTimeDragged action and handle it in the reducer. This action should update the selected item with the new start time.

## Definition of done
- [x] The start time in the selected item is updated when it's a time entry.
- [x] Tests are created

**Comment by sofokli1** [comment]
This needs to be escalated to M

The feature is too little code to quickly support add the action
- `Either` is not a thing in the code base yet
- State is empty thus adding to the issue to prep the state on all levels from app to feature to sub-feature
- Some test utils are only available in the Timer and not shared thus adding work to try and make things shared between features
