### ISSUE TITLE
Add the CloseButtonTapped action

### ISSUE THREAD

**Issue by juanlaube** [toggl/ios#210]
## Description

Add the CloseButtonTapped action and handle it in the reducer.

## Definition of done
- [ ] Set the selectedItem to nil
- [ ] Tests are created

**Comment by Odrakir** [comment]
This needs more information, also I'm guessing it's depending on other PRs. What does this close exactly?

**Comment by sofokli1** [comment]
is this for the contextual menu?

**Comment by juanlaube** [comment]
Yes, this is for the contextual menu.

**Comment by sofokli1** [comment]
isn't this called `Cancel` in the UI? and isn't this action the same as the tap outside of the CTMenu? maybe call this just `Close` and call it for both cases?

**Comment by dshr** [comment]
Currently depends on #206, will unassign myself and pick a non-Calendar issue for now
