### ISSUE TITLE
Add the DismissButtonTapped action

### ISSUE THREAD

**Issue by juanlaube** [toggl/ios#211]
## Description

Add the DismissButtonTapped action and handle it in the reducer.

## Definition of done
- [ ] Set the selectedItem to nil
- [ ] Tests are created

**Comment by sofokli1** [comment]
This could also be combined with my [comment](https://github.com/toggl/ios/issues/210#issuecomment-634004389) on #210

**Comment by dshr** [comment]
Currently depends on #206, will unassign myself and pick a non-Calendar issue for now
