### ISSUE TITLE
Add the EditButtonTapped action

### ISSUE THREAD

**Issue by juanlaube** [toggl/ios#214]
## Description

Add the EditButtonTapped action and handle it in the reducer.

## Definition of done
- [x] Move editableTimeEntry from Timer's local state to the global app state
- [x] Set the editableTimeEntry to the selectedItem's time entry in the state
- [x] Tests are created

**Comment by sofokli1** [comment]
@juanlaube I am not getting this point `Set the editableTimeEntry to the selectedItem's time entry in the state` where should this happen and when. in the app state line 17? (where the local cal state is created). in the EditButtonTapped in reducer?
