### ISSUE TITLE
Refactor start/edit buttons

### ISSUE THREAD

**Issue by Odrakir** [toggl/ios#231]
## Description
In the Start/Edit view, the buttons in the table view shouldn't be referenced by index. Also the designs show that the tags and project are on the same row in a cell that can be scrolled horizontally.

What we need to do:

- Create a new `StartEditCellType` called `buttonCell` that takes the action that needs to be dispatched when tapped.
- Create a new `StartEditCellType` called `horizontalListCell` that can be updated by inserting/removing chips to it (this can be done in another PR). It will contain a scroll view with a stack view or a collection view (whatever is easier/better). The chips will also emit actions when tapped, so they probably need their own type.
- Remove the dummy cell

## Definition of done

- [ ] The new buttonCell type is created
- [ ] The new horizontalListCell type is created.
- [ ] It contains the project and tags chips, together with the actions those buttons emit
- [ ] 🔥 The dummyCell (billable is of the new buttonCell type for now)

**Comment by Odrakir** [comment]
NOTE: The table view for this was created when we had like 6 rows there, but now the designs have changed and we only have 2 rows and they are different to each other. It might seem like an overkill to use a table view, but I think I would still use it because it makes it easier to layout stuff and also it will support further changes better than the alternatives.

**Comment by dshr** [comment]
This was made irrelevant in #302
