### ISSUE TITLE
Modal card transition discussion

### ISSUE THREAD

**Issue by sofokli1** [toggl/ios#232]
## Description
This issue is here to discuss the `Modal card presentation` transition.

Used in:
- Edit Duration
- Edit Project
- Edit TimeEntry
- Select Client
- Select Country
- Select Project
- Select Tags
- Select Color
- Select DateTime
- Send Feedback
- Start TimeEntry
- Upcoming Events Notification Settings

### Modal card presentation
It looks like this:
Old app | Aurora
------------ | -------------
The card is presented from the bottom. The height is enough to show the full content of the presented view (maxing out at a small margin from the top in cas the view need more space than the available screen). The background is covered with a grey slightly transparent color. Tapping the background will close the view | Partially opens from the bottom (we can customise per view if we want partial or full open). A drawer like handle is available at the top for dragging the view to the full open state (similar height to the old app max height) or to close the view if dragged down. The background is covered with a black transparent color. Tapping the background will not close the view.
![May-13-2020 13-46-27](https://user-images.githubusercontent.com/885122/81803329-3215c100-9520-11ea-84a3-49d2d664dc13.gif) | ![May-13-2020 14-56-46](https://user-images.githubusercontent.com/885122/81809913-c127d680-952a-11ea-9b56-cf95b3c79fbb.gif)

## Definition of done
- [ ] Agree and finalise the new transition
- [ ] Agree on the views that will use this kind of transition from the above mentioned list and if it needs to change by adding or removing views
- [ ] Agree if it  will behave as in the edit view in aurora (with partial open and full open or full open only)
- [ ] The documentation is updated to reflect the changes done in this PR (Gotta document whatever we decide here, possibly sharing ideas with the Android version)

**Comment by Odrakir** [comment]
A couple of things about the new app:
- When tapping an existing TE (running or not) the start/edit view should appear in expanded mode. Right now that's not the case, judging by your gif. Then you still can drag the handle to go to small view or dismiss.
- Tapping the background (when in small view) should attempt to close that view and show an alert if there are unsaved changes.

**Comment by sofokli1** [comment]
should we go with what was discussed in android here? https://github.com/toggl/android/issues/163#issuecomment-626834824

**Comment by smilechka** [comment]
Can we close the card by pulling the handle down?

**Comment by sofokli1** [comment]
@smilechka yes it does close the view by pulling the drawer handle.

**Comment by AlicjaSuska** [comment]
Also, @sofokli1 you've mentioned that dragging down the handle will close the view. It is a good idea (wasn't designed this way initially). Anyways, it should trigger the alert about unsaved changes as well

**Comment by sofokli1** [comment]
it will trigger it

**Comment by sofokli1** [comment]
not needed anymore
