### ISSUE TITLE
Modal dialog transition discussion

### ISSUE THREAD

**Issue by sofokli1** [toggl/ios#233]
## Description
This issue is here to discuss the Modal dialog presentation/transition.

Used in:
- Calendar Permission Denied
- No Workspace
- Paste From Clipboard
- Select Default Workspace
- Terms Of Service
- Date Range Picker (in reports)

### Modal dialog presentation
It looks like this:
The dialog/card is brought up from the bottom to the center of the screen. The background is covered with slightly transparent grey background. Tapping the background will not close the view.
![May-13-2020 13-54-13](https://user-images.githubusercontent.com/885122/81804098-43ab9880-9521-11ea-807b-77251e81dbde.gif)

## Definition of done
- [ ] Agree and finalise the new transition (if it needs changes)
- [ ] Agree on the views that will use this kind of transition from the above mentioned list and if it needs to change by adding or removing views
- [ ] The documentation is updated to reflect the changes done in this PR (Gotta document whatever we decide here, possibly sharing ideas with the Android version)

**Comment by Odrakir** [comment]
I don't think this one belongs to the Start/Edit project.

**Comment by sofokli1** [comment]
this issue is not needed anymore
