### ISSUE TITLE
Push Navigation transition discussion

### ISSUE THREAD

**Issue by sofokli1** [toggl/ios#234]
## Description
This issue is here to discuss the Push Navigation presentation/transition.

Used in:
- About
- Calendar Settings
- Forgot Password
- Licenses
- Notification Settings
- Siri Shortcuts Custom TimeEntry
- Siri Shortcuts Select Report Period
- Siri Shortcuts
- Sync Failures
- Terms And Country

### Push Navigation
It looks like this:
It is the default iOS push transition when using a navigation stack. The presented view is pushed form the tailing(right) side on top of the current view. Usually there is a navigation bar at the top where the back button is presented (this navigation bar can also be hidden if needed).
![May-13-2020 14-04-50](https://user-images.githubusercontent.com/885122/81804989-bff2ab80-9522-11ea-906e-16cf5fe58677.gif)

## Definition of done
- [ ] Agree and finalise the new transition (if it needs changes)
- [ ] Agree on the views that will use this kind of transition from the above mentioned list and if it needs to change by adding or removing views
- [ ] The documentation is updated to reflect the changes done in this PR (Gotta document whatever we decide here, possibly sharing ideas with the Android version)

**Comment by Odrakir** [comment]
Isn't this more of a design issue? I think the current implementation in settings, for example, is fine.

**Comment by sofokli1** [comment]
@AlicjaSuska most of these views open from the settings. will these view keep the same push transition or will we be changing these?

**Comment by sofokli1** [comment]
not needed anymore
