### ISSUE TITLE
Page sheet transition discussion

### ISSUE THREAD

**Issue by sofokli1** [toggl/ios#235]
## Description
This issue is here to discuss the Page sheet presentation/transition.

Used in:
- Settings
- Independent Calendar Settings (when the user first goes to the calendar view and is asked to select calendars)

### Page sheet
It looks like this:
It is similar to the [Modal card transition](https://github.com/toggl/ios/issues/232) but instead of being custom (like it), it is the default iOS provided modal presentation sheet. The background is covered with a black transparent color. Tapping the background will not close the view.
![May-13-2020 14-08-27](https://user-images.githubusercontent.com/885122/81805289-414a3e00-9523-11ea-9de4-745c1348dde8.gif)

## Definition of done
- [ ] Agree and finalise the new transition (if it needs changes)
- [ ] Agree on the views that will use this kind of transition from the above mentioned list and if it needs to change by adding or removing views
- [ ] The documentation is updated to reflect the changes done in this PR (Gotta document whatever we decide here, possibly sharing ideas with the Android version)

**Comment by Odrakir** [comment]
I think the current implementation is fine. This is the default modal for iOS 13 >. For iOS 12 < it'll be full screen. 

I see no reason to change this, unless there's something cooking in the design changes

**Comment by AlicjaSuska** [comment]
Changes is settings will be only visual. I'm not planning to change the behaviour :)

**Comment by sofokli1** [comment]
based on the above comment I am closing this issue and the 2 ref issues

**Comment by sofokli1** [comment]
@daividssilverio this conclusion may interest you
