### ISSUE TITLE
Start/edit VC should hide keyboard on scroll

### ISSUE THREAD

**Issue by sofokli1** [toggl/ios#240]
## Description
Dismiss the keyboard when scrolling the tableView since the user most likely is done typing and wants to check other content in the view
## Dependencies
none
## Definition of done
- [x] Dismiss the keyboard when scrolling the tableView

**Comment by dshr** [comment]
Apart from the short discussions this provoked, this was a rather simple issue, so I say we demote it to XS.

**Comment by dshr** [comment]
This was closed by #274.
