### ISSUE TITLE
Add the CalendarDay module boilerplate

### ISSUE THREAD

**Issue by juanlaube** [toggl/ios#263]
## Description
This needs to add the boilerplate for the calendar day module

## Definition of done
- [x] The CalendarDayAction is added
- [x] The CalendarDayState is added
- [x] The CalendarDayReducer is added
- [x] The coordinator boilerplate needed is added
- [ ] The documentation is updated to reflect the changes done in this PR

**Comment by sofokli1** [comment]
no need to mention the state action etc. just have 1 checkmark to `use the feature template` and all files will be there.

**Comment by sofokli1** [comment]
what docs need updating?
