### ISSUE TITLE
Select Color transition discussion

### ISSUE THREAD

**Issue by sofokli1** [toggl/ios#345]
## Description
This issue is here to discuss the presentation/transition of the component. Does it need changes compared to the old app? Will we keep it as is?
Ref #232
## Dependencies
None
## Definition of done
- [x] Talk with product/design to agree and finalise the transition
- [x] A new issue is created for development in case the transition is going to change (and ref this discussion for added info)

**Comment by dshr** [comment]
This one's already been defined, and the appropriate issue has been created: #412. I've added a preview to the issue as well
