### ISSUE TITLE
Add proper project persistency

### ISSUE THREAD

**Issue by heytherewill** [toggl/ios#37]
## Description
We need to persist projects in disk properly. After discussing with the sync team, we should start doing it.

## Definition of done
- [ ] CoreData is properly configured to persist projects
- [ ] A proper 1:N relationship between projects and time entries is created in the database
- [ ] The implementation, as discussed with @Odrakir, should follow the [principles of the Android implementation](https://github.com/toggl/android/blob/master/database/src/main/java/com/toggl/database/dao/ProjectDao.kt). This is to make this layer of app similar so that the sync team can act on it without much hurdle when context switching

**Comment by Odrakir** [comment]
@heytherewill why do you have update and delete methods if it's something the apps don't have?

**Comment by heytherewill** [comment]
Sync can update and delete projects

**Comment by juanlaube** [comment]
Closed by #78
