### ISSUE TITLE
Add SmartAlertsAllowAccessTapped action

### ISSUE THREAD

**Issue by sofokli1** [toggl/ios#433]
## Description
Add `SmartAlertsAllowAccessTapped` action. It should update the `UserPrefs` object in the state. Add the missing property if needed.

Also add the `RequestNotificationPermission` effect and `NotificationPermissionReceived` action

Check [notion](https://www.notion.so/toggl/Settings) for details regarding parameters and effects

## Dependencies
#417
## Definition of done
- [ ] Add SmartAlertsAllowAccessTapped action
- [ ] Add RequestNotificationPermission effect
- [ ] Add NotificationPermissionReceived action
- [ ] Add tests

**Comment by Odrakir** [comment]
I'm not sure how should this update the state... 🤔
