### ISSUE TITLE
Make sure that the generic autocomplete cell matches designs

### ISSUE THREAD

**Issue by dshr** [toggl/ios#441]
## Description
There are several cases in the app where we use an autocomplete cell with no decorations, namely for tags, clients and workspaces. Let's make sure we match the designs there.

## Definition of done
- [ ] The cell has the appropriate bg colour
- [ ] The cell has the appropriate font colour
- [ ] The cell is used for tags, clients and workspaces

**Comment by Odrakir** [comment]
I'm closing this one and creating other issues for the specific of what's left in autocomplete styling.
