### ISSUE TITLE
Request permission to calendars

### ISSUE THREAD

**Issue by juanlaube** [toggl/ios#452]
## Description

We need to request permissions to access the calendar info. Since Settings is not done yet, we will do it when the app launches and permissions were not granted yet.

## Definition of done
- [ ] The calendar usage permission message is configured in Info.plist like in the old app
- [ ] Permissions are checked in app launch
- [ ] If permissions are undetermined yet, request permissions to the read calendar info

**Comment by Odrakir** [comment]
Juan, even if we don't have settings yet, calendar permissions are also requested when entering the calendar tab, right? I think we can add an action to the calendar repo to request that.

**Comment by daividssilverio** [comment]
Yeah, for now it can be anywhere. This issue is here to get things going faster. 

The actual flow of the calendar involves requesting the permissions in the calendar tab or the settings view.
