### ISSUE TITLE
Add the week swiped action

### ISSUE THREAD

**Issue by juanlaube** [toggl/ios#466]
## Description
Add the calendar week swiped action to the date picker module. This action receives a swipe direction, either left or right.

## Dependencies
Depends on #463

## Definition of done
- [x] When swiping right, the selected date is updated to the same day in the next week in the reducer
- [x] When swiping left, the selected date is updated to the same day in the previous week in the reducer
- [ ] ~Doesn't update the selected date if the new values are not in the available dates~
- [x] When swiping right and the new selected date would end up not in the available dates, selects the last available date
- [x] When swiping left and the new selected date would end up not in the available dates, selects the first available date

**Comment by daividssilverio** [comment]
@sofokli1 I've updated the definition of done of this issue. I've noticed the problem while doing the droid bits.
