### ISSUE TITLE
Implement the DatePickerSelector

### ISSUE THREAD

**Issue by daividssilverio** [toggl/ios#584]
## Description
We need to implement a selector to convert the state of the `CalendarDatePickerState` into something that the date picker can use.

This is just an example, but this modelling seems to be enough based on the current implementation (kotlin):
Consider what you'll need in the iOS implementation, don't get hold onto this.
```kotlin
data class DatePickerViewModel(
    val weekHeaderLabels: List<DayOfWeek>,
    val weeks: List<List<SelectableDate>>,
    val selectedWeek: Int
)

data class SelectableDate(
    val dateLabel: String,
    val isSelected: Boolean,
    val isToday: Boolean
)
```

## Dependencies
This issue can be done alongside #463 

## Definition of done
- [ ] The selector is added and tested

**Comment by sofokli1** [comment]
Closing this. The date picker is already implemented and in master.
