### ISSUE TITLE
Add SSO Link UI 

### ISSUE THREAD

**Issue by pdrj** [toggl/ios#618]
## Description
Add SSO Link accounts UI. iOS details and design links https://github.com/toggl/mobileapp/issues/7417 Android https://github.com/toggl/mobileapp/issues/7418

## Definition of done

- [ ]  SSO Link accounts view is added

**Comment by sofokli1** [comment]
un-assigning myself, can't open the designs links from the linked iOS issue. not sure what is the `sso link ui`

**Comment by pdrj** [comment]
https://toggl.invisionapp.com/d/main?origin=v7#/console/19800511/430024622/preview?scrollOffset=689 we got new designs on Friday, no need to open that old link
