### ISSUE TITLE
Make the onboarding (welcome) screen configurable for SSO

### ISSUE THREAD

**Issue by pdrj** [toggl/ios#619]
## Description
Add a flag in state to tell the onboarding view how to configure itself. Then make the UI respect that flag. Details https://github.com/toggl/mobileapp/issues/7420 and https://github.com/toggl/mobileapp/issues/7421. 

The transition between the two states has to happen with a smooth animation (check the Xamarin app).

## ~~Dependencies~~ Definition of done
Flag is added to state
View is configured according to the flag (this includes adding the missing pieces, like the cancel button)
Transition between views (after hitting cancel), happens smoothly

**Comment by Odrakir** [comment]
Hey @pdrj the template on this issue looks a little funky, under **Dependencies** there seems to be the items for the **Definition of done**. On the other hand, I think this might be missing a dependency on some other issue... does it not? 🤔

**Comment by pdrj** [comment]
There are no dependencies for this one, but maybe it's best done along with #624. If something is unclear, have a look at the android PR https://github.com/toggl/android/pull/762/files or let me know.

You are right that the header is wrong, I'll change it.

**Comment by dshr** [comment]
Due to the changes in designs, this now is a separate view in it's own right (https://toggl.invisionapp.com/d/main/#/console/19800511/430024623/preview#project_console)
