### ISSUE TITLE
Add MustLinkSsoAccounts action

### ISSUE THREAD

**Issue by pdrj** [toggl/ios#634]
## Description
This action should modify the state so that the LinkSsoAccounts view is shown

## Dependencies
#633 
#618 
## Definition of done
- Action is added, reduced, tested
- It's emitted from the auth flow effect 

- [ ] The documentation is updated to reflect the changes done in this PR

**Comment by Odrakir** [comment]
Uuuhhh... 🤔 @pdrj , why is this depending on #656 ?

**Comment by pdrj** [comment]
Sorry, copy paste mistake from android. Updated.
