### ISSUE TITLE
Introduce the WaitForUndoEffect

### ISSUE THREAD

**Issue by heytherewill** [toggl/ios#65]
## Description
We need to add the effect that will actually delete time entries that are pending because of the undo.

## Dependencies
This PR needs the `CommitDeletion` action, introduced on #64 

## Definition of done
- [x] The effect that asynchronously waits for [5 seconds](https://github.com/toggl/mobileapp/blob/develop/Toggl.Core/Helper/Constants.cs#L26) and then emit a `CommitDeletion` action is added
- [x] Make actions that delete (swipes) emit the following:
  - [x] If there are no entries in the `entriesPendingDeletion` property, simply emit the `WaitForUndo` effect rather than emitting delete effects immediatelly
  - [x] If there are entries in the  `entriesPendingDeletion` property, emit effects to delete each of those entries and also the `WaitForUndo` effect.
- [x] Tests that cover all this new behavior are added

**Comment by Odrakir** [comment]
I think the conversation here is interesting as a reference: https://github.com/toggl/mobile-discussions/issues/58
