### ISSUE TITLE
Move business models mappings to repositories

### ISSUE THREAD

**Issue by Odrakir** [toggl/ios#683]
## Description
Right now we have two types of models in the app:
- DB models (`ManagedTimeEntry`) which are classes that inherit from `ManagedObject` and don't leave the DB Module
- Business models (`TimeEntry`) which are the ones used in the rest of the app including the state and the Repository

The mapping from DB models to business models is happening in the DB module. The problem with that is we need to add a lot of new properties to the models so the Repository can do syncing properly. But we don't want those properties leaking to the rest of the app.

To do this we have the following alternatives:
- Use the `ManagedTimeEntry` models in the repo and map them when moving them between the repo and the rest of the app. I don't like this option because we would expose CoreData.
- Add an additional type of model (`RepoTimeEntry`?) that has all the properties needed in the repo (most if not all of them will match the ones in the DB) and map these models to the existing business models (`TimeEntry`) when leaving the repo.
- The same as above but using an interface for the business model that only exposes the properties we need in the rest of the app (no syncing specific properties will leak)

I think number 3 will probably be the best option, but whoever takes this issue should give it a thought and decide.

WARNING: This issue is not about adding those sync only properties, it's about getting the model separation ready for it.

## Dependencies
It can probably be done before #681 , but in any case it'll requiere less conflict solving if it's done after that one.

## Definition of done
- [ ] We define and map models so there's a clear separation of them between DB <-> Repository <-> State

**Comment by simonrozsival** [comment]
I don't understand how the first option could leak `CoreData` 🤔 I suppose that the managed models (`ManagedTimeEntry`) would be mapped to the business objects (`TimeEntry`) and this way the DB layer would be encapsulated. The third option sounds like you would be leaking the managed objects. I would probably need more in-depth description of the options or to see some examples of the proposed APIs.

**Comment by Odrakir** [comment]
I mean leaking CoreData details to the Repository layer, not to the rest of the app. Option 3 avoids this by having 2 models CoreDataModel <-> RepoModel <-> BusinessModel

Option 3 is the same but BusinessModel is just an interface.
