### ISSUE TITLE
Make time entries syncable

### ISSUE THREAD

**Issue by Odrakir** [toggl/ios#684]
## Description
We need to adapt the `ManagedTimeEntry` model in CoreData and whatever repository model was created in #683 to work with sync, for that it needs:

- A local id (the one we already have) and a serverId. Check the types of these with @simonrozsival. Ideally these two should be type safe and different between each other so we don't confuse them, which could potentially happen easily. Use something like the GenericIdentifier we use currently in business models.
- The following syncable properties:  description, startTime, duration, billable, isDeleted
- The following syncable relationships: workspaceId, projectId, taskId

For the syncable properties we need 3 values for each of them:
- current (of the type of that property)
- backup (of the type of that property)
- syncStatus (.inSync, .syncNeeded, .syncing)

For the syncable relationships is the same with the caveat that while `current` will be the real CoreData relationship (mapped to an ID when exiting the DB module), `backup` on the other hand will always be the ID of the related entity. 

There are multiple ways we could do this in CoreData, but the most performant one is probably to have those plain properties in the TimeEntry model. In any case the specific approach should be decided by whoever takes this issue. Take into account that we could (should) map them to their own generic structs and enums when exiting the DB module.

## Dependencies
#683 

## Definition of done
- [ ] `id` and `serverId` are added with the appropriate types
- [ ] The rest of the sync properties and relationships are added to the DB
- [ ] Those properties are also added to the Repo models and mapped to/from the DB

**Comment by simonrozsival** [comment]
There is one more relationship that needs to be syncable and that is Tag IDs. The whole set should be syncable, not the individual tag IDs.
