### ISSUE TITLE
Make user preferences syncable

### ISSUE THREAD

**Issue by Odrakir** [toggl/ios#686]
## Description
The same way we did it for Time Entries in #684 we need to do it for the user preferences, only these are store in user defaults instead of the DB. Still the Repository model will need the same changes and the way we store the user preferences in UserDefautls needs to change to encode all those new properties as well.

When in doubt of which properties need syncing check the android implementation

## Dependencies
#684 

## Definition of done
- [ ] We add all the new needed properties to the user defaults repo model (create that model if it doesn't exist)
- [ ] We store the preferences from the repo model storing all those new properties as well.

**Comment by sofokli1** [comment]
There is a bug in the user preferences related to the either the encoding or the decoding that we do. I can't get the saved value from user defaults. it always returns the default value.

**Comment by Odrakir** [comment]
Superseded by #787
