### ISSUE TITLE
Add running time entry feature

### ISSUE THREAD

**Issue by Odrakir** [toggl/ios#69]
## Description
Add the feature that will display the card with either the running time entry with the stop button or the description textfield with the play button at the bottom of the timeline. This includes the view controller with the preliminary UI, the coordinator, the feature state and an empty reducer and actions.

This feature needs access to the currently running time entry to show its details or the empty start card if its null

## Dependencies
None

## Definition of done
- [x] The whole file structure is created inside the Timer module
- [x] The UI for both the running time entry and the small start card is created
- [x] The UI uses a selector for the current running time entry to adapt its layout
- [x] The empty reducer is created and combined with the rest into the app reducer

**Comment by sofokli1** [comment]
@Odrakir should the description text input allow for multiple lines of text (thus needing to resize the view based on text amount)?

**Comment by Odrakir** [comment]
I wouldn't resize the view, it should take the same space regardless of the content. Currently we have the moving label, not sure if this is what we want for the new app. Either talk with Alicja or do whatever you feel because design is not final right now.
