### ISSUE TITLE
Fix total tracked time for the selected day in calendar

### ISSUE THREAD

**Issue by sofokli1** [toggl/ios#713]
## Description
The label that keeps track of the total count time in the selected day is not updating when there is a running TE because the state is not updates every second so it does not update. The logic for this should be similar to the running time entry card (though not as it is right now with a timer updating the ui every second). A more elegant solution is needed. and ideally it should be implemented the same in both places. But let's stick to the calendar view for now.

## Dependencies
none

## Definition of done
- [ ] Make it work

**Comment by daividssilverio** [comment]
On android, we've used a selector to create a view model that could schedule recalculations of the header values for a specific day when there is a running time entry. 

You can check: https://github.com/toggl/android/blob/dc2d14675a87451061fe6c350749b265afb676cf/calendar/src/main/java/com/toggl/calendar/datepicker/ui/CalendarDatePickerFragment.kt#L141-L151

and https://github.com/toggl/android/blob/57819af2d5f4840e5fb520b49c3900895d9c190e/calendar/src/main/java/com/toggl/calendar/datepicker/domain/DayHeaderSelector.kt

**Comment by Odrakir** [comment]
Hey @sofokli1 what do you mean by "though not as it is right now with a timer updating the ui every second", what's specifically wrong with that approach?

**Comment by sofokli1** [comment]
Having to create a timer every time we need a running time entry seems a bit much. Also I do not like that the view is handling all of this on its own (at least in iOS the view creates and handles the timer based on the selectors).

I would prefer this timer be one in the whole app maybe something in the `TimeService` that ticks every second. This way it will be always correct and synced in the whole app and we just need to subscribe to it.

The way we are doing it now we need a timer for each instance that is showing a running timer (running TE card, edit view, calendar view, maybe other places) and these timers start based on the user input and thus are not in sync (they do not tick at the same time).

That being said, this is not the biggest issue we have right now baed on our time table.

**Comment by Odrakir** [comment]
I see... I already went ahead and created an observable in the Time service, so we can work from there #716
