### ISSUE TITLE
Add DescriptionTextFieldTapped action

### ISSUE THREAD

**Issue by Odrakir** [toggl/ios#72]
## Description
Action to show the start time entry view from the running time entry bottom card (when there's no time entry running)

## Dependencies
#69 

## Definition of done
- [ ] The Timer listens to changes in its `EditableTimeEntry?` to show the start/edit view
- [ ] The new action is added
- [ ] The new action is handled by the reducer and the `EditableTimeEntry` in the state set
- [ ] Tests are added

**Comment by heytherewill** [comment]
Superseded by cardTapped, as per docs
