### ISSUE TITLE
Add RunningTimeEntryTapped action

### ISSUE THREAD

**Issue by Odrakir** [toggl/ios#73]
## Description
Action to show the edit time entry view from the running time entry bottom card (when there's a time entry running)

## Dependencies
#69

## Definition of done
- [ ] The new action is added
- [ ] The new action is handled by the reducer and the state is changed to set the `EditableTimeEntry`
- [ ] Tests are added

**Comment by heytherewill** [comment]
Superseded by the CardTapped action from #109
