### ISSUE TITLE
Set up app flavors

### ISSUE THREAD

**Issue by heytherewill** [toggl/ios#9]
## Description
Let's configure the build system so that installing a Debug, AdHoc and release builds yield different app ids so that we can have different installed apps on our phones. *NOTE: For now, let's stick to using `com.toggl` as the base bundle ID*

## Definition of done
- [x] The app name is changed to Aurora (we will revert that once we are ready to ship)
- [x] The app icons is set to be the same as the one from the Xamarin app
- [x] The Debug AdHoc and Release builds of the app have different icons 
- [x] The Debug AdHoc and Release builds can co-exist in our phones
- [x] The debug bundle id should be `{base bundle Id}.debug`
- [x] The AdHoc bundle id should be `{base bundle Id}.adhoc`

**Comment by Odrakir** [comment]
Do we still need adhoc builds? We are doing (or should do) most testing in TestFlight anyway and until we need to distribute the app outside of the AppStore, I see no reason for them.

**Comment by amulware** [comment]
Unless someone has a better alternative, we need builds that target Staging for frequent testing. I think AdHoc builds have served us well for this.

**Comment by Odrakir** [comment]
In my opinion as much testing as possible (other than the one the developer does) should be done in release configurations just in case something changes with respect to staging. The alternative: Create a dummy account.

Are we doing any actual testing in Staging other than the occasional weird build?

@heytherewill I created an app ID for aurora: `com.toggl.aurora` some weeks ago.

**Comment by Odrakir** [comment]
In any case, not to block this: Can we setup the configurations for debug and release builds and see about adhoc when(if) we need it?

**Comment by heytherewill** [comment]
@arturs105 was this not handled by a PR already?

**Comment by Odrakir** [comment]
It was, this can be closed: https://github.com/toggl/ios/pull/23
